import uuid as _uuid
from datetime import datetime
from typing import Optional

from pydantic import BaseModel, ConfigDict

from app.models.classroom import ClassStatus, EnrollmentRole


# ---------------------------------------------------------------------------
# Class schemas
# ---------------------------------------------------------------------------

class ClassCreate(BaseModel):
    """Payload accepted when a teacher creates a new class.

    ``class_code`` is auto-generated by the backend and must not be sent
    by the client.
    """
    class_name: str
    description: Optional[str] = None
    img_link: Optional[str] = None


class ClassResponse(BaseModel):
    """Full class representation returned to API consumers."""
    id: _uuid.UUID
    class_name: str
    class_code: str
    description: Optional[str] = None
    img_link: Optional[str] = None
    status: ClassStatus
    instructor_id: _uuid.UUID
    instructor_name: Optional[str] = None
    prefect_id: Optional[_uuid.UUID] = None
    created_at: datetime
    updated_at: datetime

    model_config = ConfigDict(from_attributes=True)


# ---------------------------------------------------------------------------
# Enrollment schemas
# ---------------------------------------------------------------------------

class EnrollmentResponse(BaseModel):
    """Enrollment record returned to API consumers."""
    id: _uuid.UUID
    class_id: _uuid.UUID
    student_id: _uuid.UUID
    role: EnrollmentRole
    enrolled_at: datetime

    model_config = ConfigDict(from_attributes=True)
