"""add_class_and_enrollment_tables

Revision ID: 8e6582dd0487
Revises: a724834587c6
Create Date: 2026-06-09 08:45:53.524688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e6582dd0487'
down_revision: Union[str, Sequence[str], None] = 'a724834587c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('class_name', sa.String(), nullable=False),
    sa.Column('class_code', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('img_link', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('active', 'archived', name='classstatus'), nullable=False),
    sa.Column('instructor_id', sa.UUID(), nullable=False),
    sa.Column('prefect_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['instructor_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['prefect_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classes_class_code'), 'classes', ['class_code'], unique=True)
    op.create_index(op.f('ix_classes_id'), 'classes', ['id'], unique=False)
    op.create_table('class_enrollments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('student', 'ta', name='enrollmentrole'), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_class_enrollments_class_id'), 'class_enrollments', ['class_id'], unique=False)
    op.create_index(op.f('ix_class_enrollments_id'), 'class_enrollments', ['id'], unique=False)
    op.create_index(op.f('ix_class_enrollments_student_id'), 'class_enrollments', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_class_enrollments_student_id'), table_name='class_enrollments')
    op.drop_index(op.f('ix_class_enrollments_id'), table_name='class_enrollments')
    op.drop_index(op.f('ix_class_enrollments_class_id'), table_name='class_enrollments')
    op.drop_table('class_enrollments')
    op.drop_index(op.f('ix_classes_id'), table_name='classes')
    op.drop_index(op.f('ix_classes_class_code'), table_name='classes')
    op.drop_table('classes')
    # ### end Alembic commands ###
