"""Add is_verified, is_premium, auth_provider, badges to users

Revision ID: bc4d94a6412e
Revises: a0c946608076
Create Date: 2026-06-06 14:56:24.178107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bc4d94a6412e'
down_revision: Union[str, Sequence[str], None] = 'a0c946608076'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('users', sa.Column('is_premium', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('users', sa.Column('auth_provider', sa.String(), nullable=False, server_default='password'))
    op.add_column('users', sa.Column('badges', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'badges')
    op.drop_column('users', 'auth_provider')
    op.drop_column('users', 'is_premium')
    op.drop_column('users', 'is_verified')
    # ### end Alembic commands ###
