"""Add Class and ClassEnrollment models

Revision ID: ce09f0f9d51e
Revises: 8e6582dd0487
Create Date: 2026-06-09 08:52:13.687854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce09f0f9d51e'
down_revision: Union[str, Sequence[str], None] = '8e6582dd0487'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
